server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Media: images, icons, video, audio
    location ~* \.(?:jpg|jpeg|gif|png|ico|xml|webp|avif|svg)$ {
        add_header Cache-Control "public, max-age=31536000, no-transform";
    }

    # CSS and Javascript
    location ~* \.(?:css|js)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # WebFonts
    location ~* \.(?:ttf|ttc|otf|eot|woff|woff2)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # JSON files (like translation/locales or webmanifest)
    location ~* \.(?:json|webmanifest)$ {
        add_header Cache-Control "public, max-age=86400, must-revalidate";
    }

    # HTML and other data (routes React)
    location / {
        # IMPORTANT: Toujours renvoyer index.html pour les routes React
        try_files $uri $uri/ /index.html;

        # Disable caching for index.html to ensure clients always get the latest code reference
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}

